"""
Shared graph utilities for the naming engines.

The key insight driving this module is that using NetworkX's
``subgraph_isomorphisms_iter()`` on realistic molecule graphs is
intractably slow: for a 24-atom template matched against a 20-atom
target there can be millions of valid embeddings to enumerate before
the best one is found.

Instead we use **progressive peripheral pruning** + exact isomorphism:

1. Compute a *peripheral ordering* of the template nodes via iterative
   leaf-peeling (nodes with the lowest degree at each round are removed
   first).  These are the terminal groups (–OH, –NH2, …) that are most
   likely absent when a residue is embedded in a larger molecule.

2. Build candidate subgraphs of exactly ``target_size`` nodes by
   removing the most peripheral nodes first.  This is a DFS tree
   search where each branch swaps one node near the
   removal/retention boundary.

3. For each candidate subgraph, run **exact** graph isomorphism (fast,
   polynomial in practice for < 60-atom residues) rather than
   subgraph isomorphism (NP-complete, exponential in the gap size).

The search is bounded by ``max_candidates`` (matching candidates
yielded) and ``max_iterations`` (total DFS states explored), so
worst-case runtime is predictable and stays well under a second for
typical amino-acid/carbohydrate residues.
"""

from __future__ import annotations

from collections import Counter
from typing import Iterable, List, Tuple

import networkx as nx


def peripheral_order(graph: nx.Graph) -> List:
    """
    Return the nodes of *graph* sorted from most peripheral to most central.

    Uses iterative minimum-degree peeling (analogous to k-core
    decomposition but keeping the per-round ordering).  Nodes removed
    in the first round are leaves (degree 1), then their neighbours
    become leaves in subsequent rounds, and so on.  Ties within each
    round are broken deterministically by string representation.
    """
    order: List = []
    g = graph.copy()
    while g.number_of_nodes() > 0:
        min_deg = min(d for _, d in g.degree())
        batch = sorted(
            (n for n, d in g.degree() if d == min_deg),
            key=str,
        )
        order.extend(batch)
        g.remove_nodes_from(batch)
    return order


def iter_subgraph_candidates(
    graph: nx.Graph,
    target_size: int,
    target_element_counts: Counter,
    max_candidates: int = 32,
    max_iterations: int = 512,
) -> Iterable[Tuple[nx.Graph, float]]:
    """
    Yield ``(induced_subgraph, node_coverage)`` pairs.

    Each subgraph has exactly *target_size* nodes and its element
    composition matches *target_element_counts*.  Candidates are
    generated by a greedy DFS that removes the most peripheral
    (leaf-first) template nodes and explores swaps near the
    removal boundary to account for cases where the greedy ordering
    alone picks the wrong atoms to discard.

    Parameters
    ----------
    graph:
        Template graph to prune.
    target_size:
        Number of nodes in each candidate subgraph.
    target_element_counts:
        Required element composition (``Counter`` of element strings)
        that every yielded subgraph must satisfy.
    max_candidates:
        Stop after yielding this many element-matching candidates.
    max_iterations:
        Hard cap on total DFS states explored regardless of how many
        matching candidates were found.
    """
    n = graph.number_of_nodes()
    if target_size > n or target_size < 1:
        return

    if target_size == n:
        sg_elems = Counter(
            graph.nodes[v].get("element", "") for v in graph.nodes
        )
        if sg_elems == target_element_counts:
            yield graph, 1.0
        return

    porder = peripheral_order(graph)
    n_to_remove = n - target_size
    all_nodes = list(graph.nodes())
    rank = {v: i for i, v in enumerate(porder)}  # lower = more peripheral

    seen: set = set()
    count = 0
    iters = 0

    # Compute element surplus: how many extra atoms of each element the
    # template has compared to the target.  We use this to build an
    # element-guided initial candidate: greedily pick peripheral nodes
    # whose elements are over-represented before filling remaining slots
    # with the most peripheral remaining nodes.
    template_elems = Counter(
        graph.nodes[v].get("element", "") for v in graph.nodes
    )
    surplus: Counter = template_elems - target_element_counts  # elements to shed

    guided_removal: list = []
    for node in porder:
        if len(guided_removal) >= n_to_remove:
            break
        elem = graph.nodes[node].get("element", "")
        if surplus.get(elem, 0) > 0:
            guided_removal.append(node)
            surplus[elem] -= 1

    # Fill remaining slots from the periphery (no element constraint)
    for node in porder:
        if len(guided_removal) >= n_to_remove:
            break
        if node not in guided_removal:
            guided_removal.append(node)

    # Seed the DFS with two starting states:
    #  1. Element-guided candidate (prefer to shed over-represented elements)
    #  2. Pure-peripheral candidate (remove the n most peripheral nodes)
    initial_guided = frozenset(guided_removal)
    initial_peripheral = frozenset(porder[:n_to_remove])
    stack = [initial_peripheral, initial_guided]  # guided is processed first (LIFO)

    while stack and count < max_candidates and iters < max_iterations:
        removal_set = stack.pop()
        iters += 1

        if removal_set in seen:
            continue
        seen.add(removal_set)

        kept = [v for v in all_nodes if v not in removal_set]
        subgraph = graph.subgraph(kept)
        sg_elems = Counter(
            subgraph.nodes[v].get("element", "") for v in subgraph.nodes
        )

        if sg_elems == target_element_counts:
            node_cov = len(kept) / n
            yield subgraph, node_cov
            count += 1

        # DFS expansion: swap the *least* peripheral nodes of the
        # removal set with the *most* peripheral nodes of the kept set.
        # This moves the removal boundary inward one step at a time.
        sorted_removed = sorted(
            removal_set, key=lambda v: rank[v], reverse=True
        )  # highest rank first → least peripheral of the removed batch
        sorted_peripheral_kept = sorted(
            (v for v in all_nodes if v not in removal_set),
            key=lambda v: rank[v],
        )  # lowest rank first → most peripheral of the kept batch

        for swap_out in sorted_removed[:2]:
            for swap_in in sorted_peripheral_kept[:4]:
                new_removal = (removal_set - {swap_out}) | {swap_in}
                if len(new_removal) == n_to_remove and new_removal not in seen:
                    stack.append(new_removal)
